apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-pv
  namespace: kube-logging
spec:
  capacity:
    storage: 1Gi
  storageClassName: managed-nfs
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/catacombs/vmware/elastic
    server: 192.168.69.151
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: elastic
    name: elastic-pvc
