apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus-data
spec:
  capacity:
    storage: 100Gi
  storageClassName: managed-nfs
  accessModes:
    - ReadWriteMany
  nfs:
    path: /mnt/catacombs/repos/nexus
    server: 192.168.69.151
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: devops-tools
    name: nexus-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus-data
  namespace: devops-tools
spec:
  storageClassName: managed-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

