apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: devops-tools
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/path:   /
      prometheus.io/port:   '8081'
spec:
  selector: 
    app: nexus-server
    #type: NodePort  
  type: LoadBalancer  
  ports:
    - port: 80
      name: nexus
      targetPort: 8081
      nodePort: 32000
    - port: 8181
      name: nexus-proxy
      targetPort: 8181
      nodePort: 32001
